# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-06 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '文章类别', 'verbose_name_plural': '文章类别'},
        ),
        migrations.AlterField(
            model_name='auther',
            name='age',
            field=models.IntegerField(verbose_name='作者年龄'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.Tag', verbose_name='文章类别'),
        ),
    ]
