# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-06 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191006_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auther',
            name='auther_name',
            field=models.CharField(max_length=50, null=True, verbose_name='作者姓名'),
        ),
    ]
