# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-06 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191006_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=50, null=True, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(max_length=50, null=True, verbose_name='名称'),
        ),
    ]
